import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./providers";
import { manrope } from "@/styles/fonts";

export const metadata: Metadata = {
  title: "Victor Ebubechukwu",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={manrope.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
